# QAxServer
OBJECTS_QAXSERVER =
OBJECTS_QAXSERVER += $(QT4XHB_OBJ_DIR)/QAxBindable$(OBJEXT)
OBJECTS_QAXSERVER += $(QT4XHB_OBJ_DIR)/QAxBindableClass$(OBJEXT)
OBJECTS_QAXSERVER += $(QT4XHB_OBJ_DIR)/QAxFactory$(OBJEXT)
OBJECTS_QAXSERVER += $(QT4XHB_OBJ_DIR)/QAxFactoryClass$(OBJEXT)
