# QtDesigner
OBJECTS_QTDESIGNER = \
   $(QT4XHB_OBJ_DIR)/QAbstractExtensionFactory$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QAbstractExtensionFactoryClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QAbstractExtensionManager$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QAbstractExtensionManagerClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QAbstractFormBuilder$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QAbstractFormBuilderClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerActionEditorInterface$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerActionEditorInterfaceClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerContainerExtension$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerContainerExtensionClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerCustomWidgetCollectionInterface$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerCustomWidgetCollectionInterfaceClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerCustomWidgetInterface$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerCustomWidgetInterfaceClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerDynamicPropertySheetExtension$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerDynamicPropertySheetExtensionClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormEditorInterface$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormEditorInterfaceClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormWindowCursorInterface$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormWindowCursorInterfaceClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormWindowInterface$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormWindowInterfaceClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormWindowInterfaceSlots$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormWindowInterfaceSlotsMoc$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormWindowManagerInterface$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormWindowManagerInterfaceClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormWindowManagerInterfaceSlots$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerFormWindowManagerInterfaceSlotsMoc$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerMemberSheetExtension$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerMemberSheetExtensionClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerObjectInspectorInterface$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerObjectInspectorInterfaceClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerPropertyEditorInterface$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerPropertyEditorInterfaceClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerPropertyEditorInterfaceSlots$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerPropertyEditorInterfaceSlotsMoc$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerPropertySheetExtension$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerPropertySheetExtensionClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerTaskMenuExtension$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerTaskMenuExtensionClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerWidgetBoxInterface$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QDesignerWidgetBoxInterfaceClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QExtensionFactory$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QExtensionFactoryClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QExtensionManager$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QExtensionManagerClass$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QFormBuilder$(OBJEXT) \
   $(QT4XHB_OBJ_DIR)/QFormBuilderClass$(OBJEXT) \
