# QtScriptTools
OBJECTS_QTSCRIPTTOOLS =
OBJECTS_QTSCRIPTTOOLS += $(QT4XHB_OBJ_DIR)/QScriptEngineDebuggerClass$(OBJEXT)
OBJECTS_QTSCRIPTTOOLS += $(QT4XHB_OBJ_DIR)/QScriptEngineDebuggerSlots$(OBJEXT)
OBJECTS_QTSCRIPTTOOLS += $(QT4XHB_OBJ_DIR)/QScriptEngineDebuggerSlotsMoc$(OBJEXT)
