# QtSvg
OBJECTS_QTSVG =
OBJECTS_QTSVG += $(QT4XHB_OBJ_DIR)/QGraphicsSvgItemClass$(OBJEXT)
OBJECTS_QTSVG += $(QT4XHB_OBJ_DIR)/QSvgGeneratorClass$(OBJEXT)
OBJECTS_QTSVG += $(QT4XHB_OBJ_DIR)/QSvgRendererClass$(OBJEXT)
OBJECTS_QTSVG += $(QT4XHB_OBJ_DIR)/QSvgRendererSlots$(OBJEXT)
OBJECTS_QTSVG += $(QT4XHB_OBJ_DIR)/QSvgRendererSlotsMoc$(OBJEXT)
OBJECTS_QTSVG += $(QT4XHB_OBJ_DIR)/QSvgWidgetClass$(OBJEXT)
