//
// Qt4xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 4
//
// Copyright (c) 2025 Marcos Antonio Gambeta <marcosgambeta@outlook.com>
//

// DO NOT EDIT THIS FILE - the content was created using a source code generator

#ifndef QTOUCHEVENT_CH
#define QTOUCHEVENT_CH

// enum QTouchEvent::DeviceType
#define QTouchEvent_TouchScreen                                      0
#define QTouchEvent_TouchPad                                         1

#endif // QTOUCHEVENT_CH
