/*

  Qt4xHb - bibliotecas de ligação entre Harbour/xHarbour e Qt Framework 4

  Copyright (C) 2012-2017 Marcos Antonio Gambeta <marcosgambeta@uol.com.br>

*/

/*
  Funções nulas, para evitar erros com classes ou recursos não implementados
*/

FUNCTION Q_IPV6ADDR()
RETURN NIL

FUNCTION QAXAGGREGATED()
RETURN NIL

FUNCTION QEVENTPRIVATE()
RETURN NIL

FUNCTION QITEMEDITORFACTORY()
RETURN NIL

FUNCTION QMATRIX()
RETURN NIL

FUNCTION QMATRIX3X3()
RETURN NIL

FUNCTION QSTRING()
RETURN NIL

FUNCTION QSTRINGREF()
RETURN NIL

FUNCTION QVARIANTHASH()
RETURN NIL

FUNCTION QXMLSTREAMENTITYDECLARATIONS()
RETURN NIL

FUNCTION QXMLSTREAMNAMESPACEDECLARATIONS()
RETURN NIL

FUNCTION QXMLSTREAMNOTATIONDECLARATIONS()
RETURN NIL

FUNCTION UCHAR()
RETURN NIL

FUNCTION QFONTENGINE()
RETURN NIL

FUNCTION QPLATFORMGLCONTEXT()
RETURN NIL

FUNCTION QDECLARATIVECOMPONENTATTACHED()
RETURN NIL
