/*

  Qt4xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 4

  Copyright (C) 2021 Marcos Antonio Gambeta <marcosgambeta AT outlook DOT com>

*/

/*
  DO NOT EDIT THIS FILE - the content was created using a source code generator
*/

#include "QGraphicsWidgetSlots.h"

QGraphicsWidgetSlots::QGraphicsWidgetSlots( QObject * parent ) : QObject( parent )
{
}

QGraphicsWidgetSlots::~QGraphicsWidgetSlots()
{
}

void QGraphicsWidgetSlots::geometryChanged()
{
  QObject * object = qobject_cast< QObject * >( sender() );

  PHB_ITEM cb = Qt4xHb::Signals_return_codeblock( object, "geometryChanged()" );

  if( cb )
  {
    PHB_ITEM pSender = Qt4xHb::Signals_return_qobject( object, "QGRAPHICSWIDGET" );

    hb_vmEvalBlockV( cb, 1, pSender );

    hb_itemRelease( pSender );
  }
}

void QGraphicsWidgetSlots_connect_signal( const QString & signal, const QString & slot )
{
  QGraphicsWidget * obj = qobject_cast< QGraphicsWidget * >( Qt4xHb::getQObjectPointerFromSelfItem() );

  if( obj )
  {
    QGraphicsWidgetSlots * s = QCoreApplication::instance()->findChild<QGraphicsWidgetSlots *>();

    if( s == NULL )
    {
      s = new QGraphicsWidgetSlots();
      s->moveToThread( QCoreApplication::instance()->thread() );
      s->setParent( QCoreApplication::instance() );
    }

    hb_retl( Qt4xHb::Signals_connection_disconnection( s, signal, slot ) );
  }
  else
  {
    hb_retl( false );
  }
}
