/*

  Qt4xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 4

  Copyright (C) 2018 Marcos Antonio Gambeta <marcosgambeta AT outlook DOT com>

*/

/*
  DO NOT EDIT THIS FILE - the content was created using a source code generator
*/

#include "QObjectSlots.h"

static QObjectSlots * s = NULL;

QObjectSlots::QObjectSlots(QObject *parent) : QObject(parent)
{
}

QObjectSlots::~QObjectSlots()
{
}
void QObjectSlots::destroyed( QObject * obj )
{
  QObject *object = qobject_cast<QObject *>(sender());
  PHB_ITEM cb = Signals_return_codeblock( object, "destroyed(QObject*)" );
  if( cb )
  {
    PHB_ITEM psender = hb_itemPutPtr( NULL, (QObject *) object );
    PHB_ITEM pobj = hb_itemPutPtr( NULL, (QObject *) obj );
    hb_vmEvalBlockV( (PHB_ITEM) cb, 2, psender, pobj );
    hb_itemRelease( psender );
    hb_itemRelease( pobj );
    Signals_disconnect_signal( object, "destroyed(QObject*)" );
  }
}

HB_FUNC( QOBJECT_ONDESTROYED )
{
  if( s == NULL )
  {
    s = new QObjectSlots( QCoreApplication::instance() );
  }

  hb_retl( Signals_connection_disconnection( s, "destroyed(QObject*)", "destroyed(QObject*)" ) );
}

